general {
    before_sleep_cmd = pkill -f "quickshell.*idle-overlay"; sleep 0.5; quickshell -c ~/.config/quickshell/lockscreen
    after_sleep_cmd = quickshell -c ~/.config/quickshell/lockscreen
}

listener {
    timeout = 180
    on-timeout = quickshell -c ~/.config/quickshell/idle-overlay
    on-resume = pkill -f "quickshell.*idle-overlay"
}

listener {
    timeout = 600
    on-timeout = systemctl suspend
}
