general {
    lock_cmd = pkill -f "quickshell.*idle-overlay"; while pgrep -f "quickshell.*idle-overlay" > /dev/null; do sleep 0.05; done; pidof hyprlock || hyprlock
    before_sleep_cmd = pkill -f "quickshell.*idle-overlay"; while pgrep -f "quickshell.*idle-overlay" > /dev/null; do sleep 0.05; done; pidof hyprlock || hyprlock
    after_sleep_cmd = pkill -f "quickshell.*idle-overlay"; pidof hyprlock || hyprlock
}

listener {
    timeout = 180
    on-timeout = quickshell -c ~/.config/quickshell/idle-overlay
    on-resume = pkill -f "quickshell.*idle-overlay"
}

listener {
    timeout = 300
    on-timeout = pidof hyprlock || hyprlock
}

listener {
    timeout = 600
    on-timeout = systemctl suspend
}
